import {installNativeSelects} from './native-select.mjs';
// DOM-adapter behavioral tests. These are not real-browser visual/accessibility tests.
import fs from 'node:fs';
import assert from 'node:assert/strict';
class Element{
 constructor(id){this.id=id;this.value='';this.checked=false;this.hidden=false;this.disabled=false;this.textContent='';this._html='';this.handlers={};this.attrs={};}
 set innerHTML(value){this._html=value;}get innerHTML(){return this._html;}
 addEventListener(event,fn){(this.handlers[event]??=[]).push(fn);}
 setAttribute(key,value){this.attrs[key]=value;}
 dispatch(event){for(const fn of this.handlers[event]??[])fn();}
}
async function boot(n){const html=fs.readFileSync(new URL(`../source/web/t${n}.html`,import.meta.url),'utf8'),elements={};for(const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"[^>]*>/g)){const [tag,name,id]=match,e=elements[id]=new Element(id);e.value=tag.match(/\bvalue="([^"]*)"/)?.[1]??'';e.checked=/\bchecked\b/.test(tag);e.hidden=/\bhidden\b/.test(tag);e.disabled=/\bdisabled\b/.test(tag);if(name==='select'){const body=html.slice(match.index+tag.length).split('</select>')[0],options=[...body.matchAll(/<option\b([^>]*)>([^<]*)<\/option>/g)],option=options.find(o=>/\bselected\b/.test(o[1]))??options[0];e.value=option?.[1].match(/\bvalue="([^"]*)"/)?.[1]??option?.[2]??'';}}
 installNativeSelects(elements,html);
 globalThis.document={getElementById(id){assert.ok(elements[id],`T${n} missing #${id}`);return elements[id];}};await import(`../source/web/t${n}.js?dom-test`);
 const click=id=>{assert.equal(elements[id].disabled,false,`#${id} disabled`);elements[id].dispatch('click');};const input=(id,value,event='input')=>{if(typeof value==='boolean')elements[id].checked=value;else elements[id].value=String(value);elements[id].dispatch(event);};return {elements,click,input};}
{
 const {elements:e,click,input}=await boot(6);assert.equal(e['time-value'].textContent,'0 / 9');click('step');assert.equal(e['hidden-value'].textContent,'0.761594');click('step');assert.equal(e['hidden-value'].textContent,'0.363399');assert.equal(e['gradient-value'].textContent,'0.182256');click('finish');assert.equal(e['time-value'].textContent,'9 / 9');assert.equal(e.step.disabled,true);assert.equal(e.finish.disabled,true);
 for(let i=0;i<3;i++){click('reset');click('step');}click('reset');input('delay',24);input('recurrent',0);input('distraction',0);input('first',-1);click('finish');assert.equal(e['time-value'].textContent,'25 / 25');assert.equal(e['hidden-value'].textContent,'0.000000');assert.equal(e['gradient-value'].textContent,'0.000000');input('recurrent',1.8);assert.equal(e['time-value'].textContent,'0 / 25');input('distraction',1);click('finish');assert.ok(!e['state-chart'].innerHTML.includes('NaN'));click('reset');assert.equal(e.first.value,'1');assert.equal(e.delay.value,'8');assert.equal(e.recurrent.value,'0.5');assert.equal(e.distraction.value,'0');assert.equal(e.step.disabled,false);
}
{
 const {elements:e,click,input}=await boot(7);assert.equal(e['output-value'].textContent,'4.6790');click('equal');assert.equal(e['output-value'].textContent,'4.0000');assert.equal(e.qx.value,'0');assert.equal(e.qy.value,'0');const before=e['output-value'].textContent;input('last-value',-20);assert.equal(e['output-value'].textContent,before);input('causal',false);assert.equal(e['output-value'].textContent,'-3.5000');input('query-row',0,'change');assert.equal(e.qx.value,'1');input('causal',true);assert.equal(e['output-value'].textContent,'2.0000');input('query-row',3,'change');input('qx',4);input('qy',-4);assert.ok(Number.isFinite(Number(e['output-value'].textContent)));assert.equal(e['sum-value'].textContent,'1.000000');for(let i=0;i<4;i++){click('equal');click('reset');}assert.equal(e.causal.checked,true);assert.equal(e['query-row'].value,'1');assert.equal(e['output-value'].textContent,'4.6790');assert.ok(e['attention-chart'].innerHTML.includes('×'));
}
{
 const {elements:e,click,input}=await boot(8);assert.equal(e['length-value'].textContent,'6 / 6');assert.equal(e['prefix-value'].textContent,'待比较');assert.ok(e.parameters.textContent.includes('embedding'));click('change-last');assert.equal(e.sequence.value,'ABCABA');assert.equal(e['prefix-value'].textContent,'0.000000');click('change-last');assert.equal(e.sequence.value,'ABCABB');input('position',0,'change');assert.ok(e['stages-body'].innerHTML.includes('1.200879'));input('attention',false);assert.ok(e['block-summary'].textContent.includes('分支贡献为 0'));assert.equal(e['prefix-value'].textContent,'待比较');click('change-last');assert.equal(e['prefix-value'].textContent,'0.000000');
 input('sequence','A');assert.equal(e['length-value'].textContent,'1 / 6');assert.equal(e['prefix-value'].textContent,'无前缀');click('change-last');assert.equal(e.sequence.value,'B');const previous=e['stages-body'].innerHTML;for(const bad of ['','a','ABX','AAAAAAA','<img>']){input('sequence',bad);assert.equal(e.error.hidden,false);assert.equal(e['change-last'].disabled,true);assert.equal(e['stages-body'].innerHTML,previous);assert.equal(e.sequence.attrs['aria-invalid'],'true');}input('sequence','ABC');assert.equal(e.error.hidden,true);assert.equal(e['change-last'].disabled,false);assert.equal(e.sequence.attrs['aria-invalid'],'false');assert.equal(e['length-value'].textContent,'3 / 6');
 for(let i=0;i<3;i++){click('change-last');click('reset');}assert.equal(e.sequence.value,'ABCABC');assert.equal(e.position.value,'2');assert.equal(e.attention.checked,true);assert.equal(e['prefix-value'].textContent,'待比较');assert.equal(e['probability-value'].textContent,'1.000000');
}
{
 const {elements:e,click,input}=await boot(9);assert.equal(e['writes-value'].textContent,'0');assert.equal(e['slot-value'].textContent,'2');assert.equal(e['maximum-value'].textContent,'0.998325');click('write');assert.equal(e['writes-value'].textContent,'1');assert.ok(e['trace-body'].innerHTML.includes('[2.00000, 3.00000, 0.00000]'));click('correct-example');assert.equal(e['writes-value'].textContent,'1');click('wrong-example');assert.ok(e['trace-body'].innerHTML.includes('[1.60000, 1.80000, 0.00000]'));assert.ok(e.status.textContent.includes('从初始矩阵'));
 input('key','zero');assert.equal(e['slot-value'].textContent,'全部并列');input('beta',0);assert.equal(e['maximum-value'].textContent,'0.166667');click('clear');assert.equal(e['read-vector'].textContent,'[0.00000, 0.00000, 0.00000]');assert.equal(e['writes-value'].textContent,'0');input('slot',5);input('erase',0);input('add','C');input('write-mode','hard');click('write');assert.ok(e['trace-body'].innerHTML.includes('[0.00000, 0.00000, 1.00000]'));input('write-mode','soft');click('write');assert.equal(e['writes-value'].textContent,'2');input('write-mode','wrong');click('write');assert.equal(e['writes-value'].textContent,'3');
 click('reset');for(let i=0;i<100;i++)click('write');assert.equal(e['writes-value'].textContent,'100');assert.equal(e.write.disabled,true);click('reset');assert.equal(e.write.disabled,false);assert.equal(e.key.value,'B');assert.equal(e.slot.value,'1');assert.equal(e.beta.value,'8');assert.equal(e.erase.value,'1');assert.equal(e.add.value,'replacement');assert.equal(e['write-mode'].value,'hard');assert.equal(e['writes-value'].textContent,'0');for(let i=0;i<3;i++){click('clear');click('wrong-example');click('reset');}assert.equal(e['maximum-value'].textContent,'0.998325');
}
console.log('PASS T6–T9 DOM adapters: initial render, every control, parameter edits, deterministic reset/repeated actions, sequence validation and no mutation on invalid text, causal interventions, memory branches and 100-write bound. Real browser/layout QA remains separate.');
